version: '3'
services:
  rproxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
        - ./rproxy/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        - ./rproxy/tls:/etc/nginx/certs/
