version: '3'
services:
#  mongodb:
#    image: mongo:7.0.14
#    volumes:
#      - ./mongo/data:/data/db:delegated
#    ports:
#      - "27017:27017"
  rproxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
        - ./rproxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./rproxy/tls:/etc/nginx/certs/
