version: '3'
services:
  harness:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      - DEFAULT_ISSUER=https://auth.conformance.elevenware.com
      - ADMIN_ISSUER=https://auth.admin.conformance.elevenware.com
      - DEFAULT_CLIENT_ID=conformance_suite
      - DEFAULT_CLIENT_SECRET=abcde12345
      - ADMIN_CLIENT_ID=conformance_suite_admin
      - ADMIN_CLIENT_SECRET=abcde12345
      - ADMIN_GROUP=conformance-admins
      - DEFAULT_USER_NAME=George McIntosh
      - DEFAULT_EMAIL=george@elevenware.com
      - ADMIN_USER_NAME=George McIntosh
      - ADMIN_EMAIL=george.admin@elevenware.com
      - DEFAULT_PUBLIC_KEY=/etc/harness/keys/defaultProvider.public.key
      - DEFAULT_PRIVATE_KEY=/etc/harness/keys/defaultProvider.private.key
      - ADMIN_PUBLIC_KEY=/etc/harness/keys/adminProvider.public.key
      - ADMIN_PRIVATE_KEY=/etc/harness/keys/adminProvider.private.key
    volumes:
        - ./signingKeys:/etc/harness/keys
  rproxy:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
        - ./rproxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./rproxy/tls:/etc/nginx/certs/
